French Translation
HumanTree92/esx_advancedgarage pull request #227
Opened 2021-05-01 15:56 UTC by Firokat

May not be perfect, but it's better than nothing no ?

2021-07-12 00:02 UTC, FreakOutModz requested changes
This is a good attempt, but the chosen text uses bad French syntax, several typing errors. I do not recommend the merge of this.

2021-07-12 00:02 UTC, FreakOutModz commented on locales/fr.lua
> +	['custom_kick'] = 'INPUT CUSTOM KICK MESSAGE',
This is not french

2021-07-12 00:02 UTC, FreakOutModz commented on locales/fr.lua
> +	['pound_cars'] = 'Fourrière: Fee $%s',
This is not french

2021-07-12 04:55 UTC, closed without merging

2021-07-14 18:32 UTC, Firokat commented on locales/fr.lua
> +	['custom_kick'] = 'INPUT CUSTOM KICK MESSAGE',
This is not intended to be seen.

2021-07-14 18:37 UTC, Firokat commented
In fact, as I said in the original description, it isn't perfect and the code is free to edit. Still, the translation is fairly good and can be used.